options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Deploy the .faf parser to Cloud Run functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - faf-source-of-truth
      - --region=us-east1
      - --source=.
      - --trigger-http
      - --runtime=python312
      - --entry-point=parse_faf
      - --allow-unauthenticated

  # Step 2: Run Bi-Sync to update documentation
  - name: 'python:3.12-slim'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - name: 'python:3.12-slim'
    entrypoint: 'python'
    args: ['sync_faf.py']
